contact_links:
  - name: Question about the library
    about: Support questions are better answered in our Discord server. Issues asking how to implement a feature in your bot will be closed.
    url: https://discord.gg/r3sSKJJ
