name: test

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.x' ]

    name: pytest ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade "coverage[toml]" pytest pytest-asyncio pytest-cov pytest-mock

      - name: Install package
        run: |
          pip install -e .

      - name: Run tests
        shell: bash
        run: |
          PYTHONPATH="$(pwd)" pytest -vs --cov=discord --cov-report term-missing:skip-covered
